import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
    tr: {
        appName: 'Akıllı Sulama',
        homeTab: 'Ana Ekran',
        forecastTab: 'Tahmin',
        settingsTab: 'Ayarlar',
        aboutTab: 'Hakkında',
        fieldAnalysis: 'Tarla Analizi',
        noLocation: 'Konum girilmedi',
        analyze: 'Analiz Et',
        analyzing: 'AI analiz yapıyor, lütfen bekleyin...',
        irrigateNow: 'Sulama Gerekli',
        stressRisk: 'Stres Riski Var',
        allGood: 'Her Şey Yolunda',
        allGoodSub: 'Sulama gerekmiyor, tarlan sağlıklı',
        daysUntilStress: 'gün sonra stres bekleniyor',
        stressSoon: 'Yakın zamanda stres bekleniyor',
        detailedInfo: 'Detaylı Bilgi',
        maxTemp: 'Maks. Sıcaklık',
        soilMoisture: 'Toprak Nemi (mm)',
        rain3Days: 'Yağış 3 Gün (mm)',
        vpd: 'VPD (kPa)',
        stressLevel: 'Stres Seviyesi',
        irrigation: 'Sulama (mm)',
        aiSuggestion: 'AI Önerisi',
        waitingAnalysis: 'Analiz bekleniyor',
        waitingDesc: 'Ayarlar ekranından konumunu kaydet, ardından Analiz Et butonuna bas.',
        warningTitle: 'Uyarı',
        warningLocation: 'Önce Ayarlar ekranından konum kaydet!',
        errorTitle: 'Hata',
        errorApi: "API'ye bağlanılamadı. Backend çalışıyor mu?",
        sensorless: 'Sensörsüz',
        sensor: 'Sensörlü',
        forecastTitle: '7 Günlük Tahmin',
        wrForecast: 'Wr Tahmini',
        normal: 'Normal',
        stressRiskLabel: 'Stres Riski',
        detail: 'Detay',
        day: 'Gün',
        stress: 'Stres',
        refresh: 'Tahmini Yenile',
        loadingForecast: 'Tahmin yükleniyor...',
        noForecast: 'Tahmin verisi yok.',
        noForecastDesc: 'Önce Ayarlar ekranından konum kaydet.',
        location: 'Konum',
        manualCoords: 'Koordinat Girişi',
        lat: 'Enlem (Latitude)',
        lon: 'Boylam (Longitude)',
        modeSelect: 'Mod Seçimi',
        sensorlessDesc: 'Sadece konum yeterli. Sistem hava durumu verisini kullanır.',
        sensorDesc: 'Toprak nemi sensör değerini (Wr) girerek daha hassas tahmin alırsın.',
        sensorData: 'Sensör Verileri',
        wrInput: 'Mevcut Toprak Nemi — Wr (mm)',
        rainInput: '3 Günlük Yağış Tahmini (mm) — opsiyonel',
        save: 'Kaydet',
        saved: '✓ Kaydedildi',
        saveSuccess: 'Kaydedildi',
        saveSuccessDesc: 'Tarla ayarları başarıyla kaydedildi!',
        saveError: 'Kaydedilemedi.',
        offlineNote: 'Ayarlar cihazına kaydedilir. İnternet olmasa bile veriler korunur.',
        project: 'Proje',
        projectTeam: 'Proje Ekibi',
        projectOwner: 'Proje Sahibi',
        teamMember: 'Takım Üyesi',
        academicAdvisor: 'Akademik Danışman',
        leader: 'Lider',
        modelPerf: 'Model Performansı',
        techDetails: 'Teknik Detaylar',
        purpose: 'Projenin Amacı',
        purposeText: 'Kurak bölgelerde tarımsal su kullanım verimliliğini artırmak için yapay zeka destekli, düşük maliyetli ve özerk bir akıllı sulama sistemi geliştirmek. LSTM modeli ile toprak nemi, VPD ve hava durumu verilerini birleştirerek proaktif sulama kararları üretilmektedir.',
        aiAlgo: 'AI Algoritması',
        dataSource: 'Veri Kaynağı',
        connection: 'Bağlantı',
        workMode: 'Çalışma Modu',
        mobilePlatform: 'Mobil Platform',
        waterSaving: 'Su Tasarrufu',
        yieldIncrease: 'Verim Artışı',
        modelType: 'Model Tipi',
        rSquare: 'R² Skoru',
        latPlaceholder: 'örn: 39.9167',
        lonPlaceholder: 'örn: 32.8333',
        wrPlaceholder: 'örn: 95.0',
        rainPlaceholder: 'örn: 5.0',
        mmAmount: 'mm önerilen miktar',
        academicYear: '2025 / 2026 Akademik Yılı',
        tubitakDesc: 'Sanayi Odaklı Lisans Projesi Desteği',
        onlineOffline: 'Online + Offline',
        apiOnline: '● API Bağlı',
        apiOffline: '● API Bağlı Değil',
        apiChecking: '● Kontrol ediliyor...',
        manualIrrigation: 'Manuel Sulama',
        irrigationOn: 'Sulama açık',
        irrigationOff: 'Sulama kapalı',
        esp32Title: 'ESP32 Bağlı Değil',
        esp32OldData: 'Son sensör verisi 1 saatten eski. Wr değerini manuel girin veya Sensörsüz moda geçin.',
        esp32NoData: 'Sensörden veri alınamadı.',
        esp32Unreachable: 'Sensöre ulaşılamadı.',
        esp32ManualNo: 'Manuel sulama açılamaz. ESP32 bağlantısı yok.',
        esp32ManualNoData: 'Manuel sulama açılamaz. Sensörden veri alınamadı.',
        esp32ManualUnreachable: 'Manuel sulama açılamaz. Sensöre ulaşılamıyor.',
        irrigationCmdFail: 'Sulama komutu gönderilemedi.',
        apiConnectFail: "API'ye bağlanılamıyor.",
        sensorFetched: 'Sensör Verisi Alındı',
        sensorOldWarning: 'Son okuma 1 saatten eski',
        sensorManualInput: 'Wr değerini manuel girin.',
        selectOnMap: 'Haritadan Seç',
        mapInstruction: 'Haritaya tıklayarak konum seç',
        mapConfirm: 'Bu Konumu Kullan',
        mapCancel: 'İptal',
        navigation: 'Navigasyon',
        localStorage: 'Yerel Depolama',
        globalState: 'Global Durum',
    },
    en: {
        appName: 'Smart Irrigation',
        homeTab: 'Home',
        forecastTab: 'Forecast',
        settingsTab: 'Settings',
        aboutTab: 'About',
        fieldAnalysis: 'Field Analysis',
        noLocation: 'No location set',
        analyze: 'Analyze',
        analyzing: 'AI is analyzing, please wait...',
        irrigateNow: 'Irrigation Required',
        stressRisk: 'Stress Risk Detected',
        allGood: 'All Good',
        allGoodSub: 'No irrigation needed, field is healthy',
        daysUntilStress: 'days until stress',
        stressSoon: 'Stress expected soon',
        detailedInfo: 'Detailed Info',
        maxTemp: 'Max Temperature',
        soilMoisture: 'Soil Moisture (mm)',
        rain3Days: 'Rain 3 Days (mm)',
        vpd: 'VPD (kPa)',
        stressLevel: 'Stress Level',
        irrigation: 'Irrigation (mm)',
        aiSuggestion: 'AI Suggestion',
        waitingAnalysis: 'Waiting for analysis',
        waitingDesc: 'Save your location in Settings, then press Analyze.',
        warningTitle: 'Warning',
        warningLocation: 'Please save your location in Settings first!',
        errorTitle: 'Error',
        errorApi: 'Could not connect to API. Is the backend running?',
        sensorless: 'No Sensor',
        sensor: 'With Sensor',
        forecastTitle: '7-Day Forecast',
        wrForecast: 'Wr Forecast',
        normal: 'Normal',
        stressRiskLabel: 'Stress Risk',
        detail: 'Detail',
        day: 'Day',
        stress: 'Stress',
        refresh: 'Refresh Forecast',
        loadingForecast: 'Loading forecast...',
        noForecast: 'No forecast data.',
        noForecastDesc: 'Please save your location in Settings first.',
        location: 'Location',
        manualCoords: 'Enter Coordinates',
        lat: 'Latitude',
        lon: 'Longitude',
        modeSelect: 'Mode Selection',
        sensorlessDesc: 'Only location needed. System uses weather data.',
        sensorDesc: 'Enter soil moisture sensor value (Wr) for more precise results.',
        sensorData: 'Sensor Data',
        wrInput: 'Current Soil Moisture — Wr (mm)',
        rainInput: '3-Day Rain Forecast (mm) — optional',
        save: 'Save',
        saved: '✓ Saved',
        saveSuccess: 'Saved',
        saveSuccessDesc: 'Field settings saved successfully!',
        saveError: 'Could not save.',
        offlineNote: 'Settings are saved on your device. Data is preserved even without internet.',
        project: 'Project',
        projectTeam: 'Project Team',
        projectOwner: 'Project Owner',
        teamMember: 'Team Member',
        academicAdvisor: 'Academic Advisor',
        leader: 'Leader',
        modelPerf: 'Model Performance',
        techDetails: 'Technical Details',
        purpose: 'Project Purpose',
        purposeText: 'Developing an AI-powered, low-cost, autonomous smart irrigation system to maximize agricultural water use efficiency in arid regions.',
        aiAlgo: 'AI Algorithm',
        dataSource: 'Data Source',
        connection: 'Connection',
        workMode: 'Operation Mode',
        mobilePlatform: 'Mobile Platform',
        waterSaving: 'Water Saving',
        yieldIncrease: 'Yield Increase',
        modelType: 'Model Type',
        rSquare: 'R² Score',
        latPlaceholder: 'e.g: 39.9167',
        lonPlaceholder: 'e.g: 32.8333',
        wrPlaceholder: 'e.g: 95.0',
        rainPlaceholder: 'e.g: 5.0',
        mmAmount: 'mm recommended',
        academicYear: '2025 / 2026 Academic Year',
        tubitakDesc: 'Industry-Oriented Undergraduate Research Support',
        onlineOffline: 'Online + Offline',
        apiOnline: '● API Connected',
        apiOffline: '● API Disconnected',
        apiChecking: '● Checking...',
        manualIrrigation: 'Manual Irrigation',
        irrigationOn: 'Irrigation on',
        irrigationOff: 'Irrigation off',
        esp32Title: 'ESP32 Disconnected',
        esp32OldData: 'Last sensor reading is over 1 hour old. Enter Wr manually or switch to No-Sensor mode.',
        esp32NoData: 'Could not retrieve sensor data.',
        esp32Unreachable: 'Sensor unreachable.',
        esp32ManualNo: 'Cannot enable manual irrigation. No ESP32 connection.',
        esp32ManualNoData: 'Cannot enable manual irrigation. No sensor data.',
        esp32ManualUnreachable: 'Cannot enable manual irrigation. Sensor unreachable.',
        irrigationCmdFail: 'Failed to send irrigation command.',
        apiConnectFail: 'Cannot connect to API.',
        sensorFetched: 'Sensor Data Received',
        sensorOldWarning: 'Last reading is over 1 hour old',
        sensorManualInput: 'Please enter Wr manually.',
        selectOnMap: 'Select on Map',
        mapInstruction: 'Click on the map to select location',
        mapConfirm: 'Use This Location',
        mapCancel: 'Cancel',
        navigation: 'Navigation',
        localStorage: 'Local Storage',
        globalState: 'Global State',
    }
};

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState('tr');
    function toggleLang() {
        setLang(prev => prev === 'tr' ? 'en' : 'tr');
    }
    const t = translations[lang];
    return (
        <LanguageContext.Provider value={{ lang, toggleLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}